### ISSUE TITLE
Possibilità cercare ultime N circolari e una circolare specifica

### ISSUE THREAD

**Issue by SoftwareIISGubbio** [SoftwareIISGubbio/totem#10]
Servono due servizi in più in CircolariManager:

/circolare/{id}. per avere una sola circolare

e un modo per cercare ultime N circolari, magari mettendo parametro opzionale in più in "/circolari?N=4" ad esempio per cercare le ultime

**Comment by chiararo0si** [comment]
lavoro completato, con il commit 1127d2e5849156f4fa7524528499e1466f1af0a2
